# Generated by Django 5.2.2 on 2025-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_category_sight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sight_images/'),
        ),
        migrations.AddField(
            model_name='sight',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
