# Generated by Django 5.2.2 on 2025-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_sight_cover_image_sight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='construction_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
